version: '3'
services:
  global:
    image: "mysql:5.7"
    ports:
      - "33333:3306"
    volumes:
      - ./db_dumps/global:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "global"
      MYSQL_USER: "global"
      MYSQL_PASSWORD: "passglobal"

  shard:
    image: "mysql:5.7"
    ports:
      - "33334:3306"
    volumes:
      - ./db_dumps/shard:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "shard"
      MYSQL_USER: "shard"
      MYSQL_PASSWORD: "passglobal"

  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command: "-DV"
